export const AllowedLanguages = ['en', 'cs'];

export const Translations = {
  'our_team_en': 'Our team',
  'our_team_cs': 'Náš tým',
  'our_projects_en': 'Our projects',
  'our_projects_cs': 'Naše projekty',
  'company_contact_en': 'If you are interested in cooperation or detailed information, please contact us at',
  'company_contact_cs': 'V případě zájmu o spolupráci nebo detailních informací nás prosím kontaktujte na',
  'cooperation_en': {
    'title': 'Opportunities for cooperation',
    'content': 'In Mild Blue we create solutions to improve medical care utilizing data already generated by the system. We use artificial intelligence and machine learning to carry on where traditional monitoring and reporting stops.<br><br>Mild Blue is here to help you improve your products and services. Be it medical data analysis, custom made algorithms or end-to-end solutions.'
  },
  'cooperation_cs': {
    'title': 'Možnosti spolupráce',
    'content': 'V Mild Blue vytváříme nástroje zlepšující péči o pacienty s využitím dostupných dat. Zapojujeme umělou inteligenci a strojové učení, abychom navázali tam, kde obvykle monitorování a reporting končí.<br><br>Mild Blue je s vámi, ať se jedná o optimalizaci využívání nástrojů, analýzu dat, algoritmy na míru nebo kompletní řešení.'
  }
}
